name: Tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Install
        run: python setup.py install
      - name: Tests
        run: python -m unittest
