name: Tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: sudo apt-get install libhdf5-dev
      - run: pip install Cython numpy pkgconfig
      - name: Build
        run: python setup.py build
      - name: Install
        run: python setup.py install
      - name: Tests
        run: python -m unittest test
